//! Embeds the split sprite tree (`assets/sprites/**`) into the binary as the fallback
//! art source for release builds and any run outside the repo checkout. Dev runs load
//! the folder directly at startup instead (see `assets::sprite_sheet`), so editing a
//! sprite PNG never needs a rebuild.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).expect("read assets/sprites") {
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            walk(&path, out);
        } else if path.extension().is_some_and(|e| e == "png")
            && !path.to_string_lossy().ends_with(".bak.png")
        {
            out.push(path);
        }
    }
}

fn main() {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("assets/sprites");
    // Cargo rescans directories recursively for rerun-if-changed.
    println!("cargo:rerun-if-changed={}", root.display());

    let mut files = Vec::new();
    walk(&root, &mut files);
    files.sort();

    let mut src = String::from(
        "// Generated by build.rs — the embedded copy of assets/sprites/**.\n\
         pub static EMBEDDED_SPRITE_MANIFEST: &str =\n    include_str!(",
    );
    src.push_str(&format!("{:?});\n", root.join("manifest.txt").display()));
    src.push_str("pub static EMBEDDED_SPRITE_PARTS: &[(&str, &[u8])] = &[\n");
    for f in &files {
        let rel = f
            .strip_prefix(&root)
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        src.push_str(&format!(
            "    ({rel:?}, include_bytes!({:?})),\n",
            f.display()
        ));
    }
    src.push_str("];\n");

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("sprite_parts.rs");
    fs::write(out, src).expect("write sprite_parts.rs");
}
