//! Byte-for-byte parity tests for `level::level_gen` against the real Java
//! `fdoom.level.LevelGen` running on the JVM.
//!
//! # How the reference dumps were produced
//!
//! The files in `tests/data/levelgen_*.bin` were generated by compiling the REAL
//! Fossicker Java sources (`fdoom.level.LevelGen` and its full dependency tree,
//! including the real `Tiles` registry, so tile ids are the real ones) with `javac`,
//! plus a small `GenDump` harness that:
//!
//! - applies the same standalone fixes as `LevelGen.main` (`Game.gameDir = "";
//!   Tiles.initTileList();`),
//! - sets `Settings.set("type", ...)` / `Settings.set("theme", ...)`,
//! - injects the world seed into the private static `LevelGen.worldSeed` field via
//!   reflection and invokes the private `createAndValidateSkyMap` /
//!   `createAndValidateTopMap` / `createAndValidateDungeon` method directly — exactly
//!   the dispatch `createAndValidateMap(w, h, level)` performs after
//!   `worldSeed = WorldGenDisplay.getSeed()` (the interactive seed input, replaced here
//!   by the injected value),
//! - writes `result[0]` (tiles) followed by `result[1]` (data) — 2 * w * h bytes.
//!
//! One deviation was required: `HistoryGen` (graveyard placement on surface maps)
//! creates a fresh *time-seeded* `new Random()` per instance in Java, so real Java
//! surface maps are NOT reproducible from the world seed alone. In the harness only,
//! `HistoryGen`'s `rand` field was changed to a shared static `Random` seeded once per
//! dump (the sequence of calls on the Random is unchanged). The Rust port mirrors this
//! by threading an explicit `history_random: &mut JavaRandom` through
//! `create_and_validate_map` (in-game callers pass `g.random`, per PORTING.md's rule for
//! incidental randomness). Everything else — the noise generation, all validation loops,
//! the HistoryGen algorithm itself, tile ids — is the unmodified Java code.
//!
//! Each dump is named `levelgen_s<worldSeed>_l<level>[_<Type>_<Theme>].bin`; type/theme
//! default to Island/Normal. Every dump is 128x128 and verified byte-identical here:
//! tiles array then data array.

use fdoom::java_random::JavaRandom;
use fdoom::level::level_gen;
use fdoom::level::tile::Tiles;

fn check_parity(
    world_seed: i64,
    level: i32,
    history_seed: i64,
    gen_type: &str,
    theme: &str,
    file: &str,
) {
    let tiles = Tiles::new();
    let mut history_random = JavaRandom::new(history_seed);

    let (map, data) = level_gen::create_and_validate_map(
        128,
        128,
        level,
        &tiles,
        world_seed,
        gen_type,
        theme,
        &mut history_random,
    )
    .expect("valid level index");

    let path = format!("{}/tests/data/{}", env!("CARGO_MANIFEST_DIR"), file);
    let expected = std::fs::read(&path).unwrap_or_else(|e| panic!("cannot read {path}: {e}"));
    assert_eq!(
        expected.len(),
        2 * 128 * 128,
        "bad reference dump size for {file}"
    );

    let (exp_map, exp_data) = expected.split_at(128 * 128);
    assert_eq!(
        map.as_slice(),
        exp_map,
        "tile array mismatch vs JVM for {file}"
    );
    assert_eq!(
        data.as_slice(),
        exp_data,
        "data array mismatch vs JVM for {file}"
    );
}

#[test]
fn surface_seed_256() {
    check_parity(256, 0, 1000, "Island", "Normal", "levelgen_s256_l0.bin");
}

#[test]
fn underground_seed_256() {
    // JAVA: levels -1..-3 redirect to the top-map generator.
    check_parity(256, -1, 1001, "Island", "Normal", "levelgen_s256_l-1.bin");
}

#[test]
fn sky_seed_256() {
    check_parity(256, 1, 1002, "Island", "Normal", "levelgen_s256_l1.bin");
}

#[test]
fn dungeon_seed_256() {
    check_parity(256, -4, 1003, "Island", "Normal", "levelgen_s256_l-4.bin");
}

#[test]
fn surface_seed_11206432() {
    check_parity(
        11206432,
        0,
        2000,
        "Island",
        "Normal",
        "levelgen_s11206432_l0.bin",
    );
}

#[test]
fn underground_seed_11206432() {
    check_parity(
        11206432,
        -1,
        2001,
        "Island",
        "Normal",
        "levelgen_s11206432_l-1.bin",
    );
}

#[test]
fn sky_seed_11206432() {
    check_parity(
        11206432,
        1,
        2002,
        "Island",
        "Normal",
        "levelgen_s11206432_l1.bin",
    );
}

#[test]
fn dungeon_seed_11206432() {
    check_parity(
        11206432,
        -4,
        2003,
        "Island",
        "Normal",
        "levelgen_s11206432_l-4.bin",
    );
}

/* type/theme branch coverage (surface, seed 256) — covers all four terrain types and
all five themes across the tests in this file. */

#[test]
fn surface_mountain_hell() {
    check_parity(
        256,
        0,
        3000,
        "Mountain",
        "Hell",
        "levelgen_s256_l0_Mountain_Hell.bin",
    );
}

#[test]
fn surface_box_desert() {
    check_parity(
        256,
        0,
        3001,
        "Box",
        "Desert",
        "levelgen_s256_l0_Box_Desert.bin",
    );
}

#[test]
fn surface_irregular_forest() {
    check_parity(
        256,
        0,
        3002,
        "Irregular",
        "Forest",
        "levelgen_s256_l0_Irregular_Forest.bin",
    );
}

#[test]
fn surface_island_plain() {
    check_parity(
        256,
        0,
        3003,
        "Island",
        "Plain",
        "levelgen_s256_l0_Island_Plain.bin",
    );
}
