//! Embedded game resources (Java loaded these from the jar via `getResourceAsStream`).
//!
//! The sprite atlas is stitched at load time from the split art files under
//! `assets/sprites/**` (see docs/ART_GUIDE.md): straight from the folder when running
//! inside the repo (instant art iteration — edit a PNG, relaunch, done), or from the
//! build-time embedded copy everywhere else (release builds, installed binaries).

use std::path::{Path, PathBuf};

use crate::gfx::SpriteSheet;

// EMBEDDED_SPRITE_MANIFEST + EMBEDDED_SPRITE_PARTS, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/sprite_parts.rs"));

/// Load the sprite atlas: the `assets/sprites/` folder if present, else the embedded
/// copy. A present-but-broken folder panics loudly rather than silently falling back —
/// an artist mid-edit should never wonder why their change isn't showing.
pub fn sprite_sheet() -> SpriteSheet {
    match sprites_dir() {
        Some(dir) => {
            let manifest = std::fs::read_to_string(dir.join("manifest.txt"))
                .unwrap_or_else(|e| panic!("read {}/manifest.txt: {e}", dir.display()));
            let owned = read_sprite_parts(&dir);
            let parts: Vec<(&str, &[u8])> = owned
                .iter()
                .map(|(p, b)| (p.as_str(), b.as_slice()))
                .collect();
            SpriteSheet::from_parts(&manifest, &parts)
        }
        None => SpriteSheet::from_parts(EMBEDDED_SPRITE_MANIFEST, EMBEDDED_SPRITE_PARTS),
    }
}

/// The split-sprites folder, when running inside the repo checkout (dev builds and
/// tests find it via the baked crate path; `cargo run` from the repo root also works
/// from a moved checkout via the relative path).
pub fn sprites_dir() -> Option<PathBuf> {
    [
        Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/sprites"),
        PathBuf::from("assets/sprites"),
    ]
    .into_iter()
    .find(|dir| dir.join("manifest.txt").is_file())
}

/// All sprite part PNGs under `dir`, as (`manifest-relative path`, bytes). Skips
/// `*.bak.png` (pixel_studio session backups).
pub fn read_sprite_parts(dir: &Path) -> Vec<(String, Vec<u8>)> {
    let mut parts = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        for entry in std::fs::read_dir(&d).unwrap_or_else(|e| panic!("read {}: {e}", d.display())) {
            let path = entry.expect("dir entry").path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|e| e == "png")
                && !path.to_string_lossy().ends_with(".bak.png")
            {
                let rel = path
                    .strip_prefix(dir)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                let bytes =
                    std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
                parts.push((rel, bytes));
            }
        }
    }
    parts.sort();
    parts
}

pub const ANTIDOUS_TXT: &str = include_str!("../assets/antidous.txt");
pub const STORY_GUIDE_TXT: &str = include_str!("../assets/story_guide.txt");

pub const SOUND_PLAYER_HURT: &[u8] = include_bytes!("../assets/playerhurt.wav");
pub const SOUND_PLAYER_DEATH: &[u8] = include_bytes!("../assets/death.wav");
pub const SOUND_MONSTER_HURT: &[u8] = include_bytes!("../assets/monsterhurt.wav");
pub const SOUND_FUSE: &[u8] = include_bytes!("../assets/fuse.wav");
pub const SOUND_EXPLODE: &[u8] = include_bytes!("../assets/explode.wav");
pub const SOUND_PICKUP: &[u8] = include_bytes!("../assets/pickup.wav");
pub const SOUND_CRAFT: &[u8] = include_bytes!("../assets/craft.wav");
pub const SOUND_SELECT: &[u8] = include_bytes!("../assets/select.wav");
pub const SOUND_CONFIRM: &[u8] = include_bytes!("../assets/confirm.wav");

pub const LOCALIZATIONS: &[(&str, &str)] = &[(
    "english",
    include_str!("../assets/localization/english.mcpl"),
)];
