//! winit `KeyCode` → Java `KeyEvent.VK_*` name mapping.
//!
//! Java's InputHandler identified keys by the names of the `VK_` constants (via
//! reflection); the keymap strings ("SHIFT-Q", "F3", "EQUALS", ...) reference those names,
//! so this table must produce them exactly.

use winit::keyboard::KeyCode;

pub fn java_key_name(code: KeyCode) -> Option<&'static str> {
    Some(match code {
        KeyCode::KeyA => "A",
        KeyCode::KeyB => "B",
        KeyCode::KeyC => "C",
        KeyCode::KeyD => "D",
        KeyCode::KeyE => "E",
        KeyCode::KeyF => "F",
        KeyCode::KeyG => "G",
        KeyCode::KeyH => "H",
        KeyCode::KeyI => "I",
        KeyCode::KeyJ => "J",
        KeyCode::KeyK => "K",
        KeyCode::KeyL => "L",
        KeyCode::KeyM => "M",
        KeyCode::KeyN => "N",
        KeyCode::KeyO => "O",
        KeyCode::KeyP => "P",
        KeyCode::KeyQ => "Q",
        KeyCode::KeyR => "R",
        KeyCode::KeyS => "S",
        KeyCode::KeyT => "T",
        KeyCode::KeyU => "U",
        KeyCode::KeyV => "V",
        KeyCode::KeyW => "W",
        KeyCode::KeyX => "X",
        KeyCode::KeyY => "Y",
        KeyCode::KeyZ => "Z",
        KeyCode::Digit0 => "0",
        KeyCode::Digit1 => "1",
        KeyCode::Digit2 => "2",
        KeyCode::Digit3 => "3",
        KeyCode::Digit4 => "4",
        KeyCode::Digit5 => "5",
        KeyCode::Digit6 => "6",
        KeyCode::Digit7 => "7",
        KeyCode::Digit8 => "8",
        KeyCode::Digit9 => "9",
        KeyCode::ArrowUp => "UP",
        KeyCode::ArrowDown => "DOWN",
        KeyCode::ArrowLeft => "LEFT",
        KeyCode::ArrowRight => "RIGHT",
        KeyCode::Enter => "ENTER",
        KeyCode::NumpadEnter => "ENTER",
        KeyCode::Escape => "ESCAPE",
        KeyCode::Space => "SPACE",
        KeyCode::ShiftLeft | KeyCode::ShiftRight => "SHIFT",
        KeyCode::ControlLeft | KeyCode::ControlRight => "CTRL",
        KeyCode::AltLeft | KeyCode::AltRight => "ALT",
        KeyCode::Backspace => "BACKSPACE",
        KeyCode::Tab => "TAB",
        KeyCode::CapsLock => "CAPS_LOCK",
        KeyCode::Delete => "DELETE",
        KeyCode::Home => "HOME",
        KeyCode::End => "END",
        KeyCode::PageUp => "PAGE_UP",
        KeyCode::PageDown => "PAGE_DOWN",
        KeyCode::Insert => "INSERT",
        KeyCode::Minus => "MINUS",
        KeyCode::Equal => "EQUALS",
        KeyCode::BracketLeft => "OPEN_BRACKET",
        KeyCode::BracketRight => "CLOSE_BRACKET",
        KeyCode::Backslash => "BACK_SLASH",
        KeyCode::Semicolon => "SEMICOLON",
        KeyCode::Quote => "QUOTE",
        KeyCode::Comma => "COMMA",
        KeyCode::Period => "PERIOD",
        KeyCode::Slash => "SLASH",
        KeyCode::Backquote => "BACK_QUOTE",
        KeyCode::F1 => "F1",
        KeyCode::F2 => "F2",
        KeyCode::F3 => "F3",
        KeyCode::F4 => "F4",
        KeyCode::F5 => "F5",
        KeyCode::F6 => "F6",
        KeyCode::F7 => "F7",
        KeyCode::F8 => "F8",
        KeyCode::F9 => "F9",
        KeyCode::F10 => "F10",
        KeyCode::F11 => "F11",
        KeyCode::F12 => "F12",
        KeyCode::Numpad0 => "NUMPAD0",
        KeyCode::Numpad1 => "NUMPAD1",
        KeyCode::Numpad2 => "NUMPAD2",
        KeyCode::Numpad3 => "NUMPAD3",
        KeyCode::Numpad4 => "NUMPAD4",
        KeyCode::Numpad5 => "NUMPAD5",
        KeyCode::Numpad6 => "NUMPAD6",
        KeyCode::Numpad7 => "NUMPAD7",
        KeyCode::Numpad8 => "NUMPAD8",
        KeyCode::Numpad9 => "NUMPAD9",
        KeyCode::NumpadAdd => "ADD",
        KeyCode::NumpadSubtract => "SUBTRACT",
        KeyCode::NumpadMultiply => "MULTIPLY",
        KeyCode::NumpadDivide => "DIVIDE",
        _ => return None,
    })
}
